package Day0922;

public class Exception01 {
	public static void main(String[] args) {
		try {
			System.out.println(calc(2, 0, '+'));
			System.out.println(calc(2, 0, '?'));
			System.out.println(calc(2, 0, '/'));
		}catch(Exception e) {
			System.out.println(e.getMessage());
//			e.printStackTrace();
			System.out.println("예외 발생");
		}finally {
			System.out.println("계산기 종료");
		}
		System.out.println("밖");
		
	}
	
	// 두 정수와 산술 연산자가 주어졌을 때 산술연산의 결과를 알려주는 메서드
	// 메서드명 : calc
	// return type : double
	static double calc(int a, int b, char op) {
		switch(op) {
		case '+':
			return a+b;
		case '-':
			return a-b;
		case '*':
			return a*b;
		case '/':
			return a/b;
		default:
			return 9999;
		}
	}
}
